spring:
  application:
    name: demo

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/foo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

redisson:
  single-server-config:
    address: "redis://localhost:6379"
    connection-minimum-idle-size: 5
    connection-pool-size: 20
    idle-connection-timeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus

bulk-insert:
  max-size: 5000
  chunk-size: 1000
  retry-milliseconds: 2000,5000